version: 1

update_configs:
  - package_manager: "javascript"
    directory: "/"
    update_schedule: "monthly"
  - package_manager: "github_actions"
    directory: "/"
    update_schedule: "monthly"
