name: Audit Workflow

on:
  schedule:
    - cron: "0 2 * * *" # run at 2 AM UTC

jobs:
  audit:
    name: Audit
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node 12.13 LTS
        uses: actions/setup-node@v2.1.0
        with:
          node-version: 12.13
      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - uses: actions/cache@v1
        id: yarn-cache
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - name: Install NPM dependencies
        run: yarn install
      - name: Audit with Yarn
        run: yarn audit
