name: CD/CI Workflow

on: [push]

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Use Node 12.13 LTS
        uses: actions/setup-node@v1
        with:
          node-version: 12.13
      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - uses: actions/cache@v1
        id: yarn-cache
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - name: Install NPM dependencies
        run: yarn install
      - name: Lint with TSLint
        run: yarn run lint
      - name: Build
        run: yarn run build

  deploy:
    if: github.ref == 'refs/heads/master'
    name: Deploy
    needs: check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Deploy with Heroku
        run: git push https://heroku:${{ secrets.HEROKU_API_KEY }}@git.heroku.com/simple-mailer-frontend.git HEAD:master -f
